"""Put the three static builds into one folder for GitHub Pages.

    python -m tools.site.assemble                         # site/dist + bi/dist + dbt docs -> _site/

    _site/              the portfolio site            (site/dist, Observable Framework)
    _site/bi/           the BI pages                  (bi/dist, Observable Framework)
    _site/dbt-docs/     dbt docs, as built in production (dbt/target/static_index.html, one self-contained file)

The three builds stay independent: each one can be previewed on its own, and a failure in one is visible in
the step that builds it. This script only copies, checks that every part is there, and adds `.nojekyll` so
GitHub Pages serves files and folders that start with an underscore (Framework writes `_observablehq/`).
Without production dbt docs (a local run), a small placeholder page says where they come from.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

PLACEHOLDER = """<!doctype html><meta charset="utf-8"><title>dbt docs</title>
<body style="font-family:Helvetica,Arial,sans-serif;background:#E4E4E1;color:#0B0B0B;padding:3rem;max-width:40rem">
<h1 style="text-transform:uppercase">dbt docs</h1>
<p>The dbt docs are generated by the production deploy (<code>dbt docs generate --static</code>) and published here
with the site. This local build has no production docs.</p><p><a href="../">Back to the project</a></p></body>
"""


def copy_tree(src: Path, dst: Path) -> None:
    if not (src / "index.html").exists():
        raise SystemExit(f"{src}/index.html not found: build it first (npm run build in {src.parent.name}/).")
    shutil.copytree(src, dst, dirs_exist_ok=True)


def assemble(site: Path, bi: Path, dbt_target: Path, out: Path) -> dict:
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    copy_tree(site, out)
    copy_tree(bi, out / "bi")
    docs = out / "dbt-docs"
    docs.mkdir()
    static = dbt_target / "static_index.html"
    if static.exists():
        shutil.copyfile(static, docs / "index.html")
        dbt_docs = "production"
    else:
        (docs / "index.html").write_text(PLACEHOLDER, encoding="utf-8")
        dbt_docs = "placeholder"
    (out / ".nojekyll").write_text("", encoding="utf-8")
    files = sum(1 for p in out.rglob("*") if p.is_file())
    return {"out": str(out), "files": files, "dbt_docs": dbt_docs}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Assemble site + BI + dbt docs for GitHub Pages.")
    parser.add_argument("--site", default="site/dist")
    parser.add_argument("--bi", default="bi/dist")
    parser.add_argument("--dbt-target", default="dbt/target")
    parser.add_argument("--out", default="_site")
    args = parser.parse_args(argv)
    result = assemble(ROOT / args.site, ROOT / args.bi, ROOT / args.dbt_target, ROOT / args.out)
    print(f"{result['out']}: {result['files']} files, dbt docs: {result['dbt_docs']}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
